spring:
  application:
    name: Urosk Taskomir Demo
  data:
    mongodb:
      uri: mongodb://root:rootpassword@localhost:50001/taskomir?authSource=admin
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false


server:
  port: 8888


taskomir:
  primary: false
  cleanupInterval: 30s
  succeededRetentionTime: 24h
  deletedRetentionTime: 7d
  poolSize: 2
  queueCapacity: 1000 # Maximum number of jobs in the queue
  instanceId: TaskomirDemoDashboard




vaadin:
  allowed-packages: net.urosk.*

logging:
  level:
    root: info
    org.atmosphere: error
    net.urosk: debug